### PR TITLE
Issue 116 - Save and read API Key from local file

### PR DESCRIPTION
**Pull request by ulf1**
See Issue https://github.com/quandl/quandl-python/issues/116

### CODE REVIEW

**Comment by ulf1** [comment]
Is this addition of any interest to you?

**Comment by mbasset** [comment]
Thanks for the submission @ulf1,

We have been busy on other projects atm however this seems like a good idea. Will try and get someone to review this next week.

**Comment by mbasset** [comment]
One immediate suggestion would be to have the config read the key if it is preset automatically rather than requiring the user to explicitly make that call.

**Comment by ulf1** [comment]
Sure change the readme

**Pull request merged**
